// src/data.js
import image1 from './img/car1.jpeg';
import image2 from './img/car2.jpeg';
import image3 from './img/car3.jpg';
import image4 from './img/car1.jpeg';
import image5 from './img/car2.jpeg';
import image6 from './img/car3.jpg';
import image7 from './img/car1.jpeg';
import image8 from './img/car2.jpeg';
import image9 from './img/car3.jpg';
const car_data= [
    {
      id: 1,
      name: 'Cappuccino',
      price: 8,
      bakery:'Minden-Bakery',
      image:image8,
    },
    {
      id: 2,
      name: 'Matcha Latte',
      price: 10,
      bakery:'Minden-Bakery',
      image:image1,
    },
    {
      id: 3,
      name: 'Golden Latte',
      price: 8,
      bakery:'Minden-Bakery',
      image:image3,
    },
    {
      id: 4,
      name: 'Hot Chocolate',
      price: 12,
      bakery:'Minden-Bakery',
      image:image9,
    },
    {
      id: 5,
      name: 'Iced Latte',
      price: 12,
      bakery:'Minden-Bakery',
      image:image2,
    },
    {
      id: 6,
      name: 'Plain Croissant',
      price: 20,
      bakery:'Minden-Bakery',
      image:image4,
    },{
      id: 7,
      name: 'French Macaron',
      price: 30,
      bakery:'Minden-Bakery',
      image:image5,
    },{
      id: 8,
      name: 'Original Blend Coffee',
      price: 12.99,
      bakery:'Minden-Bakery',
      image:image6,
    },
    {
      id: 9,
      name: 'Energy Cookie',
      price: 28,
      bakery:'Minden-Bakery',
      image:image7,
    },
    {
      id: 10,
      name: 'Cappuccino',
      price: 8,
      bakery:'Minden-Bakery',
      image:image8,
    },
    {
      id: 11,
      name: 'Matcha Latte',
      price: 10,
      bakery:'Minden-Bakery',
      image:image1,
    },
    {
      id: 12,
      name: 'Golden Latte',
      price: 8,
      bakery:'Minden-Bakery',
      image:image3,
    },
    {
      id: 13,
      name: 'Hot Chocolate',
      price: 12,
      bakery:'Minden-Bakery',
      image:image9,
    },
    {
      id: 14,
      name: 'Iced Latte',
      price: 12,
      bakery:'Minden-Bakery',
      image:image2,
    },
    {
      id: 15,
      name: 'Plain Croissant',
      price: 20,
      bakery:'Minden-Bakery',
      image:image4,
    },{
      id: 16,
      name: 'French Macaron',
      price: 30,
      bakery:'Minden-Bakery',
      image:image5,
    },{
      id: 17,
      name: 'Original Blend Coffee',
      price: 12.99,
      bakery:'Minden-Bakery',
      image:image6,
    },
    {
      id: 18,
      name: 'Energy Cookie',
      price: 28,
      bakery:'Minden-Bakery',
      image:image7,
    },
    {
      id: 19,
      name: 'Cappuccino',
      price: 8,
      bakery:'Minden-Bakery',
      image:image8,
    },
    {
      id: 20,
      name: 'Matcha Latte',
      price: 10,
      bakery:'Minden-Bakery',
      image:image1,
    },
    {
      id: 21,
      name: 'Golden Latte',
      price: 8,
      bakery:'Minden-Bakery',
      image:image3,
    },
    {
      id: 22,
      name: 'Hot Chocolate',
      price: 12,
      bakery:'Minden-Bakery',
      image:image9,
    },
    {
      id: 23,
      name: 'Iced Latte',
      price: 12,
      bakery:'Minden-Bakery',
      image:image2,
    },
    {
      id: 24,
      name: 'Plain Croissant',
      price: 20,
      bakery:'Minden-Bakery',
      image:image4,
    },{
      id: 25,
      name: 'French Macaron',
      price: 30,
      bakery:'Minden-Bakery',
      image:image5,
    },{
      id: 26,
      name: 'Original Blend Coffee',
      price: 12.99,
      bakery:'Minden-Bakery',
      image:image6,
    },
    {
      id: 27,
      name: 'Energy Cookie',
      price: 28,
      bakery:'Minden-Bakery',
      image:image7,
    },
    {
      id: 28,
      name: 'Cappuccino',
      price: 8,
      bakery:'Minden-Bakery',
      image:image8,
    },
    {
      id: 29,
      name: 'Matcha Latte',
      price: 10,
      bakery:'Minden-Bakery',
      image:image1,
    },
    {
      id: 30,
      name: 'Golden Latte',
      price: 8,
      bakery:'Minden-Bakery',
      image:image3,
    },
    {
      id: 31,
      name: 'Hot Chocolate',
      price: 12,
      bakery:'Minden-Bakery',
      image:image9,
    },
    {
      id: 32,
      name: 'Iced Latte',
      price: 12,
      bakery:'Minden-Bakery',
      image:image2,
    },
    {
      id: 33,
      name: 'Plain Croissant',
      price: 20,
      bakery:'Minden-Bakery',
      image:image4,
    },{
      id: 34,
      name: 'French Macaron',
      price: 30,
      bakery:'Minden-Bakery',
      image:image5,
    },{
      id: 35,
      name: 'Original Blend Coffee',
      price: 12.99,
      bakery:'Minden-Bakery',
      image:image6,
    },
    {
      id: 36,
      name: 'Energy Cookie',
      price: 28,
      bakery:'Minden-Bakery',
      image:image7,
    },
    {
      id: 37,
      name: 'Cappuccino',
      price: 8,
      bakery:'Minden-Bakery',
      image:image8,
    },
    {
      id: 38,
      name: 'Matcha Latte',
      price: 10,
      bakery:'Minden-Bakery',
      image:image1,
    },
    {
      id: 39,
      name: 'Golden Latte',
      price: 8,
      bakery:'Minden-Bakery',
      image:image3,
    },
    {
      id: 40,
      name: 'Hot Chocolate',
      price: 12,
      bakery:'Minden-Bakery',
      image:image9,
    },
    {
      id: 41,
      name: 'Iced Latte',
      price: 12,
      bakery:'Minden-Bakery',
      image:image2,
    },
    {
      id: 42,
      name: 'Plain Croissant',
      price: 20,
      bakery:'Minden-Bakery',
      image:image4,
    },{
      id: 43,
      name: 'French Macaron',
      price: 30,
      bakery:'Minden-Bakery',
      image:image5,
    },{
      id: 44,
      name: 'Original Blend Coffee',
      price: 12.99,
      bakery:'Minden-Bakery',
      image:image6,
    },
    {
      id: 45,
      name: 'Energy Cookie',
      price: 28,
      bakery:'Minden-Bakery',
      image:image7,
    },
  ];
  
  export default car_data;
  